CREATE SEQUENCE Secao_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Genero_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Editora_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Autor_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Create Secao
CREATE TABLE Secao ( 
 	ID NUMBER,
 	Nome VARCHAR(50) NOT NULL,  
	 
 	CONSTRAINT pk_Secao PRIMARY KEY(ID),
	CONSTRAINT uk_Secao_Nome UNIQUE(Nome)  
); 

CREATE OR REPLACE TRIGGER gera_secao_id
BEFORE INSERT ON Secao
FOR EACH ROW
BEGIN
SELECT Secao_seq.nextval INTO :new.id FROM dual;
END;

-- Create Genero
CREATE TABLE Genero ( 
 	ID NUMBER,
 	Nome VARCHAR(100) NOT NULL,
 	ID_Secao INT NOT NULL,
	 
 	CONSTRAINT pk_Genero PRIMARY KEY(ID),
	CONSTRAINT uk_Genero UNIQUE(Nome, ID_Secao),
 	CONSTRAINT fk_Secao FOREIGN KEY(ID_Secao) 
 		REFERENCES Secao(ID) ON DELETE CASCADE
);

CREATE OR REPLACE TRIGGER gera_genero_id
BEFORE INSERT ON Genero
FOR EACH ROW
BEGIN
SELECT Genero_seq .nextval INTO :new.id FROM dual;
END;

-- Create Editora
CREATE TABLE Editora ( 
	ID NUMBER,
 	Nome VARCHAR(50) NOT NULL, 
	
 	CONSTRAINT pk_Editora PRIMARY KEY(ID),
	CONSTRAINT uk_Editora UNIQUE(Nome)
); 

CREATE OR REPLACE TRIGGER gera_editora_id
BEFORE INSERT ON Editora
FOR EACH ROW
BEGIN
SELECT Editora_seq.nextval INTO :new.id FROM dual;
END;

-- Create Livro
CREATE TABLE Livro ( 
 	ISBN NUMBER(13,0) NOT NULL,
 	Titulo VARCHAR(200),  
 	Ano INT,  
 	Preco NUMBER(10,2) NOT NULL,  
 	Estoque INT NOT NULL,  
 	Descricao VARCHAR(3000),  
 	ID_Editora INT NOT NULL,
 
	CONSTRAINT pk_Livro PRIMARY KEY (ISBN),
 	CONSTRAINT fk_Editora FOREIGN KEY (ID_Editora) 
		REFERENCES Editora(ID) ON DELETE CASCADE,
	CHECK(Preco >= 0)
);