WITH CTE_AVG_Min_Max_Year
AS(
    select EXTRACT(YEAR FROM DATA_COMPRA) AS Ano,
    MIN(TOTAL) AS MINTotal,
    MAX(TOTAL) AS MAXTotal
    FROM COMPRA
    GROUP BY EXTRACT(YEAR FROM DATA_COMPRA)
)
SELECT AVG(MINTotal) AS AVG_MIN,
AVG(MAXTotal) AS AVG_MAX
FROM CTE_AVG_Min_Max_Year;